name: Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  renovate-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 24

      - name: Install Renovate CLI
        run: npm install -g renovate

      - name: Validate Renovate config
        run: renovate-config-validator --strict
